name: ML Vetting
evals:
- name: CudaKernel
  type: vetnode.evaluations.cuda_eval.CUDAEval
  requirements:
    - cuda-python
    - numpy
- name: Check GPU
  type: vetnode.evaluations.gpu_eval.GPUEval
  max_temp:  30
  max_used_memory: 0.2
- name: NCCL
  type: vetnode.evaluations.nccl_eval.NCCLEval
  scheduler: slurm
  payload: 4GB
  min_bandwidth: 15gbit
  warmup:
    payload: 256MB
    runs: 3
  requirements:
      - ['torch', '--index-url', 'https://download.pytorch.org/whl/cu126']
      - numpy