name: Simple Configuration
evals:
- name: CudaKernel
  type: vetnode.evaluations.cuda_eval.CUDAEval
  requirements:
    - cuda-python
    - numpy
- name: Check GPU
  type: vetnode.evaluations.gpu_eval.GPUEval
  max_temp:  80
  max_used_memory: 0.25
- name: Random
  type: vetnode.evaluations.random.RandomEval