name: Local Node Vetting
evals:
- name: Random
  type: vetnode.evaluations.random.RandomEval
- name: Check GPU
  type: vetnode.evaluations.gpu_eval.GPUEval
  max_temp:  30
  max_used_memory: 0.2
- name: CUDANCCLEval
  type: vetnode.evaluations.nccl_eval.CUDANCCLEval
  scheduler: slurm
  payload: 2 GB
  method: broadcast
  min_bandwidth: 20 GB/s
  warmup:
    payload: 256 MB
    runs: 2
  requirements:
      - cuda-python