name: Local Node Vetting
evals:
- name: Random
  type: vetnode.evaluations.random.RandomEval
- name: NCCL
  type: vetnode.evaluations.nccl_eval.NCCLEval
  scheduler: slurm
  requirements:
      - ['torch', '--index-url', 'https://download.pytorch.org/whl/cu126"']