name: Default Node Vetting
evals:
- name: CudaKernel
  type: vetnode.evaluations.cuda_eval.CUDAEval
  requirements:
    - cuda-python
    - numpy
- name: Check GPU
  type: vetnode.evaluations.gpu_eval.GPUEval
  max_temp:  30
  max_used_memory: 0.2