name: Simple Configuration
evals:
- name: Pinger
  type: ping-nodes
- name: CudaKernel
  type: cuda-eval
- name: Check GPU
  type: gpu-eval
  max_temp:  80
  max_used_memory: 0.25
- name: Random
  type: random